---
name: misspell

# only run on potential publishes
on:
  push:
    branches:
      - main
    paths:
      - "src/validate_plist_xml/__init__.py"
      - ".github/workflows/tag_and_release.yaml"

jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        # skip this if run through ACT
        if: ${{ !env.ACT }}
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          reporter: github-check  # Change reporter.
